services: docker

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic
    - APP_ENV=testing
  matrix:
    - distro: fedora24
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: fedora25
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: ubuntu1604
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distro: ubuntu1404
      run_opts: ""

before_install:
  - travis_retry composer self-update
  - docker pull thenodi/docker-${distro}-valet:latest

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit

  # Start the container in detached mode
  - >
    CONTAINER_ID=$( \
        docker run --rm --detach \
            --volume="${PWD}":/workspace \
            -e "REPOSITORY=/workspace" \
            ${run_opts} \
            thenodi/docker-${distro}-valet:latest
    )

  # Wait for entrypoint script to complete
  - docker exec -it $CONTAINER_ID bash -c 'echo "Waiting for entrypoint script..."; while [ ! -f /tmp/entrypoint_done ]; do sleep 1; done; echo "Entrypoint ready."'

  # Run functional tests
  - docker exec -it -u valet $CONTAINER_ID /workspace/tests/Functional/run.sh
